hydra:
  run:
    dir: data/output/${model_name}/${dataset_name}/${mode}/${now:%Y-%m-%d-%H-%M-%S}
  job:
    name: ${mode}
    chdir: false
  sweep:
    dir: ${hydra.run.dir}
    subdir: ./

model_name: CGF-NET
dataset_name: Diffusion_Plate

mode: "train"
checkpoint: ""
seed: 0
input_dir: "data/input"
output_dir: ${hydra:run.dir}
